import { createContext, useContext } from 'react'

export type ThemeMode = 'light' | 'dark'
export type Language = 'en' | 'fr'

export type UiPreferencesContextValue = {
  language: Language
  locale: string
  setSidebarCollapsed: (collapsed: boolean) => void
  setLanguage: (language: Language) => void
  setThemeMode: (themeMode: ThemeMode) => void
  sidebarCollapsed: boolean
  t: (key: TranslationKey) => string
  themeMode: ThemeMode
  toggleSidebarCollapsed: () => void
  toggleLanguage: () => void
  toggleThemeMode: () => void
}

export const uiStorageKeys = {
  language: 'brim-expense-language',
  sidebarCollapsed: 'brim-expense-sidebar-collapsed',
  themeMode: 'brim-expense-theme-mode',
}

const en = {
  'actions.approve': 'Approve',
  'actions.import': 'Import',
  'actions.preview': 'Preview',
  'actions.refresh': 'Refresh',
  'actions.runFullScan': 'Run full scan',
  'actions.scanTransactions': 'Scan transactions',
  'actions.scanning': 'Scanning...',
  'app.demoData': 'Test data',
  'app.demoDataBody': 'Sample people, receipts, approvals, and budgets keep this workspace safe to explore.',
  'app.name': 'PolyPilot',
  'app.subtitle': 'Finance co-pilot',
  'app.workspace': 'Finance workspace',
  'approvals.description':
    'Move flagged transactions into manager-ready decision packets with policy, risk, and budget context.',
  'approvals.eyebrow': 'Decide',
  'approvals.title': 'Approvals',
  'compliance.allSeverities': 'All severities',
  'compliance.allStatuses': 'All statuses',
  'compliance.amountCad': 'Amount CAD',
  'compliance.approvalEvidenceNeeded': 'Approval evidence needed',
  'compliance.category': 'Category',
  'compliance.compliant': 'Compliant',
  'compliance.contextNeeded': 'Context needed',
  'compliance.critical': 'Critical',
  'compliance.date': 'Date',
  'compliance.department': 'Department',
  'compliance.departmentsWithOpenFlags': 'Departments with open flags',
  'compliance.description':
    'See which transactions need a closer look, why they were flagged, and what to do next.',
  'compliance.details': 'Details',
  'compliance.employee': 'Employee',
  'compliance.employeesWithOpenFlags': 'Employees with open flags',
  'compliance.evidenceNote':
    'The provided transaction CSV does not include receipt or approval attachments. Evidence-related findings indicate documents required by policy, not confirmed missing documents.',
  'compliance.eyebrow': 'Review',
  'compliance.excludedNonExpense': 'Excluded non-expense',
  'compliance.filterByPolicyStatus': 'Filter by policy status',
  'compliance.filterBySeverity': 'Filter by severity',
  'compliance.findings': 'Transaction-level findings',
  'compliance.findingsBody': 'One row per transaction, with merged policy and risk details.',
  'compliance.high': 'High',
  'compliance.highCritical': 'High/Critical',
  'compliance.individualFlags': 'Individual flags',
  'compliance.lastScanSummary': 'Last scan completed in {duration} across {batches} batches.',
  'compliance.loading': 'Loading policy results...',
  'compliance.low': 'Low',
  'compliance.medium': 'Medium',
  'compliance.merchant': 'Merchant',
  'compliance.missing': 'Missing',
  'compliance.mlProgressTitle': 'ML analysis in progress',
  'compliance.needContext': 'Context needed',
  'compliance.needPreapproval': 'Approval evidence needed',
  'compliance.needReceipt': 'Receipt evidence required',
  'compliance.needsContext': 'Context needed',
  'compliance.needsPreapproval': 'Approval evidence needed',
  'compliance.needsReceipt': 'Receipt evidence required',
  'compliance.nextAction': 'Next action',
  'compliance.noFindings': 'No policy findings yet.',
  'compliance.noOpenPolicyFlags': 'No open policy flags.',
  'compliance.policyDetail': 'policy detail',
  'compliance.policyDetails': 'policy details',
  'compliance.policyViolation': 'Policy violation',
  'compliance.policyViolations': 'Policy violations',
  'compliance.policyScan': 'Policy scan',
  'compliance.policyScanBody': 'Run the layered compliance, risk, and review-queue refresh workflow.',
  'compliance.reviewRequired': 'Review required',
  'compliance.scanStageFinalizing': 'Finalizing',
  'compliance.scanStageFinalizingBody': 'Refreshing queue summaries, repeat offenders, and next actions.',
  'compliance.scanStagePolicy': 'Policy rules',
  'compliance.scanStagePolicyBody': 'Checking uploaded policy rules against each imported transaction.',
  'compliance.scanStageQueue': 'Review queue',
  'compliance.scanStageQueueBody': 'Merging policy and risk findings into reviewer-ready cases.',
  'compliance.scanStageRisk': 'Risk signals',
  'compliance.scanStageRiskBody': 'Scoring duplicates, split patterns, cash activity, FX, and metadata anomalies.',
  'compliance.scanned': 'Scanned',
  'compliance.score': 'Score',
  'compliance.severity': 'Severity',
  'compliance.status': 'Status',
  'compliance.sortedByRisk': 'Sorted by severity, score, and amount.',
  'compliance.syntheticDepartment': 'Assigned department',
  'compliance.syntheticEmployee': 'Assigned employee',
  'compliance.title': 'Review Queue',
  'compliance.violation': 'Violation',
  'compliance.violations': 'Violations',
  'dashboard.backendBoundary': 'Connection status',
  'dashboard.backendChecking': 'Checking connection...',
  'dashboard.backendOffline': 'Connection unavailable. You can still browse the current workspace.',
  'dashboard.backendOnline': 'Connected and returning live totals.',
  'dashboard.departmentCount': 'Departments',
  'dashboard.description':
    'Meet PolyPilot, understand the workspace, and choose the next step with real context.',
  'dashboard.employeeCount': 'Employees',
  'dashboard.eyebrow': 'Overview',
  'dashboard.heroBadge': 'Meet PolyPilot',
  'dashboard.heroDescription':
    'Use one workspace to import spend, review grounded policy and risk signals, ask follow-up questions, and move cleanly into approvals or reports.',
  'dashboard.heroEyebrow': 'Finance operations',
  'dashboard.heroSignalOne': 'Transactions imported',
  'dashboard.heroSignalPending': 'Loading',
  'dashboard.heroSignalThree': 'Needs review',
  'dashboard.heroSignalThreeValue': 'Ready',
  'dashboard.heroSignalTwo': 'People mapped',
  'dashboard.heroTitle': 'PolyPilot turns imported spend into grounded finance decisions.',
  'dashboard.introAskBody': 'Keep the assistant close when you need quick answers, summaries, or a handoff into the larger Ask view.',
  'dashboard.introAskLabel': 'Ask with context',
  'dashboard.introImportBody': 'Bring in card exports, normalize them, and keep the raw-to-clean path visible from the start.',
  'dashboard.introImportLabel': 'Start from imported data',
  'dashboard.introReviewBody': 'Policy, risk, and approvals stay tied to real records instead of floating above them as disconnected analytics.',
  'dashboard.introReviewLabel': 'Review grounded signals',
  'dashboard.normalizedCount': 'Transactions',
  'dashboard.overlayOneLabel': 'Policy checks',
  'dashboard.overlayOneValue': 'Thresholds being watched',
  'dashboard.overlayThreeLabel': 'Travel example',
  'dashboard.overlayThreeValue': 'Marketing trip spend',
  'dashboard.overlayTwoLabel': 'Risk review',
  'dashboard.overlayTwoValue': 'Signals ready',
  'dashboard.rawRows': 'Raw rows',
  'dashboard.primaryAction': 'Start import',
  'dashboard.sceneBadge': 'Live view',
  'dashboard.sceneBody': 'A neural sphere turns imported spend into connected signals, active inference pulses, and visible exception flares.',
  'dashboard.sceneLabel': 'Neural spend map',
  'dashboard.secondaryAction': 'Ask Poly',
  'dashboard.signalBody': 'These are the only live signals shown here: connection state and imported workspace coverage.',
  'dashboard.signalConnection': 'Connection',
  'dashboard.signalConnectionChecking': 'Checking',
  'dashboard.signalConnectionOffline': 'Unavailable',
  'dashboard.signalConnectionOnline': 'Connected',
  'dashboard.signalDepartments': 'Departments mapped',
  'dashboard.signalFootnote': 'Overview stays introductory on purpose. Deeper counts and review pressure live on the workflow pages where they can be explained.',
  'dashboard.signalImported': 'Imported transactions',
  'dashboard.signalPeople': 'Mapped employees',
  'dashboard.signalTitle': 'Live workspace signals',
  'dashboard.signalUnavailable': 'Unavailable',
  'dashboard.storyPrimaryLabel': 'Finance lead',
  'dashboard.storyPrimaryValue': 'Move from import to decision without leaving the workspace.',
  'dashboard.storySecondaryLabel': 'Control layer',
  'dashboard.storySecondaryValue': 'Policy, risk, and approvals stay grounded in persisted data.',
  'dashboard.storyTertiaryLabel': 'Operations pulse',
  'dashboard.storyTertiaryValue': 'Keep the next review-ready expense package in focus.',
  'dashboard.title': 'Overview',
  'dashboard.workflowApproveBody': 'Open manager-ready decisions with policy, risk, budget, and recommendation context already assembled.',
  'dashboard.workflowApproveLabel': 'Approve',
  'dashboard.workflowBody': 'This route is here to orient the team, not drown them in charts. Follow the flow below when you are ready to work.',
  'dashboard.workflowImportBody': 'Load a card export, preview the cleanup, and establish the source data PolyPilot will work from.',
  'dashboard.workflowImportLabel': 'Import',
  'dashboard.workflowReportBody': 'Generate report packages only after the underlying records and review state are ready to travel with them.',
  'dashboard.workflowReportLabel': 'Report',
  'dashboard.workflowReviewBody': 'See which transactions need attention and why, with grounded findings instead of decorative metrics.',
  'dashboard.workflowReviewLabel': 'Review',
  'dashboard.workflowTitle': 'How the workspace flows',
  'import.amountCad': 'Amount CAD',
  'import.category': 'Category',
  'import.chooseCsv': 'Choose CSV file',
  'import.csvText': 'CSV text',
  'import.dataSourceHint': 'Comma or tab-delimited data',
  'import.date': 'Date',
  'import.description':
    'Upload a card export, review the cleaned rows, then import it into your workspace.',
  'import.errorsTitle': 'Row errors',
  'import.eyebrow': 'Import',
  'import.fingerprint': 'Fingerprint',
  'import.importComplete': 'Import complete',
  'import.inserted': 'Inserted',
  'import.merchant': 'Merchant',
  'import.missingColumns': 'Missing columns',
  'import.missingColumnsTitle': 'Missing required columns',
  'import.placeholder': 'Paste CSV or TSV rows here',
  'import.previewTitle': 'Preview',
  'import.previewBody': 'Check the cleaned-up rows before you bring them in.',
  'import.previewRowsLabel': 'Preview rows',
  'import.readinessLabel': 'Import readiness',
  'import.readinessNeedsAttention': 'Needs attention',
  'import.readinessReady': 'Ready',
  'import.row': 'Row',
  'import.rowErrors': 'Row errors',
  'import.rowsReady': 'Rows ready',
  'import.sourceLabel': 'Source',
  'import.sourcePasted': 'Pasted CSV text',
  'import.skipped': 'Skipped',
  'import.statusTitle': 'Import status',
  'import.syntheticEmployee': 'Assigned employee',
  'import.title': 'Import',
  'import.transactions': 'transactions.',
  'import.unassigned': 'Unassigned',
  'policyRules.description':
    'Review reimbursement rules, draft new policy logic, and test activation flow through the backend service.',
  'policyRules.eyebrow': 'Setup',
  'policyRules.title': 'Policy Setup',
  'policyRules.activate': 'Activate',
  'policyRules.activationNote':
    'Draft and disabled rules are safe to edit. Only active rules are enforced during policy scans and appear in Compliance findings.',
  'policyRules.activated': 'Rule activated.',
  'policyRules.active': 'Active',
  'policyRules.allRules': 'All rules',
  'policyRules.critical': 'Critical',
  'policyRules.disabled': 'Rule disabled.',
  'policyRules.disabledStatus': 'Disabled',
  'policyRules.disable': 'Disable',
  'policyRules.draft': 'Draft',
  'policyRules.draftJson': 'Draft JSON preview',
  'policyRules.draftWorkbench': 'Draft workbench',
  'policyRules.draftWorkbenchBody': 'Paste policy text, shape a draft JSON rule, then validate before activation.',
  'policyRules.high': 'High',
  'policyRules.invalidJson': 'Draft JSON is not valid JSON.',
  'policyRules.invalidRule': 'Invalid rule',
  'policyRules.loadError': 'Could not load policy rules.',
  'policyRules.loading': 'Loading policy rules...',
  'policyRules.low': 'Low',
  'policyRules.manualDraftDescription': 'Manual draft rule from the Policy Rules workbench.',
  'policyRules.matchedCount': '{count} sample matches',
  'policyRules.medium': 'Medium',
  'policyRules.noRules': 'No policy rules found for this filter.',
  'policyRules.policyText': 'Policy text',
  'policyRules.policyTextPlaceholder': 'Paste a reimbursement clause or manager-defined spending rule here.',
  'policyRules.ruleCode': 'Rule code',
  'policyRules.ruleLibrary': 'Rule library',
  'policyRules.ruleLibraryBody': 'Seeded and manager-authored rules remain editable through backend endpoints.',
  'policyRules.ruleName': 'Rule name',
  'policyRules.runScan': 'Run scan',
  'policyRules.saveDraft': 'Save draft',
  'policyRules.saveError': 'Could not save draft rule.',
  'policyRules.savedDraft': 'Draft rule saved.',
  'policyRules.scanComplete': 'Scan complete: {count} transactions scanned, {flags} policy details persisted.',
  'policyRules.scanError': 'Could not run policy scan.',
  'policyRules.saving': 'Saving...',
  'policyRules.severity': 'Severity',
  'policyRules.test': 'Test',
  'policyRules.testError': 'Could not test policy rule.',
  'policyRules.testing': 'Testing...',
  'policyRules.testResult': 'Test result',
  'policyRules.updateError': 'Could not update policy rule.',
  'policyRules.validateTest': 'Validate/test',
  'policyRules.validationFailed': 'Rule validation needs attention.',
  'policyRules.validationPassed': 'Rule validation passed.',
  'policyRules.validRule': 'Valid rule',
  'reports.description':
    'Generate expense reports with line items, policy flags, risk flags, concise summaries, and CSV export.',
  'reports.eyebrow': 'Report',
  'reports.title': 'Reports',
  'routes.approvals.description': 'Work through decisions waiting on a manager.',
  'routes.approvals.label': 'Approvals',
  'routes.compliance.description': 'See which transactions need a closer look.',
  'routes.compliance.label': 'Review',
  'routes.dashboard.description': 'Meet PolyPilot, check workspace readiness, and choose the next step.',
  'routes.dashboard.label': 'Overview',
  'routes.import.description': 'Bring in a card export and import the cleaned rows.',
  'routes.import.label': 'Import',
  'routes.policyRules.description': 'Manage the rules behind your review flow.',
  'routes.policyRules.label': 'Policy Setup',
  'routes.reports.description': 'Create and export report packages.',
  'routes.reports.label': 'Reports',
  'routes.talkToData.description': 'Ask plain-language questions about spend.',
  'routes.talkToData.label': 'Ask',
  'routes.transactions.description': 'Browse the cleaned and mapped transactions.',
  'routes.transactions.label': 'Transactions',
  'scaffold.aiBoundary': 'Safety checks',
  'scaffold.aiBoundaryBody': 'Answers and automation stay inside validated backend rules.',
  'scaffold.currentMilestone': 'What this page helps with',
  'scaffold.currentMilestoneBody': 'Start with imports, then move into review and approvals.',
  'scaffold.dataSource': 'Imported records',
  'scaffold.dataSourceBody': 'Transactions, findings, and workflow history live in one place.',
  'shell.collapseSidebar': 'Collapse sidebar',
  'shell.expandSidebar': 'Expand sidebar',
  'shell.language': 'French',
  'shell.notifications': 'Notifications',
  'shell.search': 'Search',
  'shell.switchLanguage': 'Switch language',
  'shell.switchTheme': 'Switch theme',
  'shell.themeDark': 'Night mode',
  'shell.themeLight': 'Day mode',
  'talkToData.description':
    'Ask plain-language questions about spend and get a grounded answer you can trust.',
  'talkToData.eyebrow': 'Ask',
  'talkToData.activeContext': 'Using {title} context',
  'talkToData.activeSession': 'Active {id}',
  'talkToData.artifactCurrent': 'Current artifact',
  'talkToData.artifactPreview': '{label} preview',
  'talkToData.artifacts': 'Artifacts',
  'talkToData.ask': 'Ask',
  'talkToData.asking': 'Asking...',
  'talkToData.chatFirstBody':
    'Poly in the dock and this full workspace share the same session, so you can start anywhere and come here when the answer needs more room.',
  'talkToData.chatFirstTitle': 'Chat first',
  'talkToData.citations': 'Citations',
  'talkToData.conversation': 'Conversation',
  'talkToData.conversationBody':
    'Ask naturally, keep following up, and pull in the current app context when you need it.',
  'talkToData.copyPreview': 'Copy Preview',
  'talkToData.dismiss': 'Dismiss',
  'talkToData.downloadBrief': 'Download Brief',
  'talkToData.downloadCsv': 'Download CSV',
  'talkToData.downloadDiagram': 'Download Diagram',
  'talkToData.downloadPreview': 'Download Preview',
  'talkToData.emptyGrounding': 'Policy questions can cite retrieved clauses and flagged findings.',
  'talkToData.emptySpend': 'Spend questions return totals, counts, averages, and groups.',
  'talkToData.emptyWorkspace':
    'Use the dock from any page, then come here when the answer needs charts, tables, or exports.',
  'talkToData.filtersAndFocus': 'Filters and focus',
  'talkToData.generatedFiles': 'Generated files',
  'talkToData.generatedFilesBody':
    'Preview the artifact instantly, then download a backend-generated file when you want to keep it.',
  'talkToData.grounding': 'Grounding',
  'talkToData.loadingSession': 'Loading session',
  'talkToData.newSession': 'New session',
  'talkToData.noExtraFilters': 'This answer did not need extra filters.',
  'talkToData.noRows': 'No rows returned for this question.',
  'talkToData.overview': 'Overview',
  'talkToData.placeholder': 'Ask about spend, policy, or risk...',
  'talkToData.result': 'Result',
  'talkToData.resultPreview': 'Result preview',
  'talkToData.selectedAnswer': 'Selected answer',
  'talkToData.selectedAnswerEmpty': 'Pick an assistant response to inspect the plan, results, and exports.',
  'talkToData.suggestedAsks': 'Suggested asks',
  'talkToData.title': 'Ask Questions',
  'talkToData.valid': 'Valid',
  'talkToData.validated': 'Validated',
  'talkToData.validation': 'Validation',
  'talkToData.validationBody':
    'Requests are validated before any backend workflow runs. Unsupported plans are blocked before execution.',
  'talkToData.blocked': 'Blocked',
  'approvals.advisoryRecommendation': 'Advisory recommendation',
  'approvals.allApprovals': 'All approvals',
  'approvals.approved': 'Approved',
  'approvals.approving': 'Approving...',
  'approvals.budgetSnapshot': 'Budget snapshot',
  'approvals.budgetUnavailable': 'Budget snapshot is unavailable.',
  'approvals.cancelled': 'Cancelled',
  'approvals.creating': 'Creating...',
  'approvals.decision': 'Decision',
  'approvals.decisionNote': 'Decision note',
  'approvals.decisionPacket': 'Decision packet',
  'approvals.decisionPacketBody':
    'Select or create an approval request to inspect the recommendation, budget context, and audit-ready decision controls.',
  'approvals.decisionSaved': 'Decision saved by {actor}{timestamp}.',
  'approvals.decided': 'Decided',
  'approvals.denied': 'Denied',
  'approvals.deny': 'Deny',
  'approvals.denying': 'Denying...',
  'approvals.filterStatus': 'Filter approval status',
  'approvals.groundedInputs': 'Grounded inputs',
  'approvals.loadingApprovals': 'Loading approvals...',
  'approvals.loadingCandidates': 'Loading approval candidates...',
  'approvals.managerDecisionBody':
    'Start here when a flagged transaction needs someone to decide what happens next.',
  'approvals.managerDecisionTitle': 'Needs a manager decision',
  'approvals.missingInformation': 'Missing information',
  'approvals.monthRemaining': 'Month remaining',
  'approvals.needsDecision': 'Needs a decision',
  'approvals.noApprovals': 'No approval requests yet.',
  'approvals.noManagerWaiting': 'Nothing is waiting on a manager right now.',
  'approvals.noneRecorded': 'None recorded.',
  'approvals.openApproval': 'Open approval',
  'approvals.openApprovals': 'Open approvals',
  'approvals.priorApprovals': 'Prior approvals',
  'approvals.priority': 'Priority {value}',
  'approvals.quarterRemaining': 'Quarter remaining',
  'approvals.quarterSpend': 'Quarter spend',
  'approvals.recommend': 'Recommend {value}',
  'approvals.refresh': 'Refresh',
  'approvals.requested': 'Requested',
  'approvals.reviewerBrief': 'Reviewer brief',
  'approvals.savedApprovalsBody': 'Requests that have already been created.',
  'approvals.savedApprovalsTitle': 'Saved approvals',
  'approvals.saving': 'Saving...',
  'approvals.spendHistory': 'Employee spend history',
  'approvals.spendHistoryUnavailable': 'Spend history snapshot is unavailable.',
  'approvals.totalSpend': 'Total spend',
  'approvals.transactions': 'Transactions',
  'approvals.urgent': 'Urgent',
  'approvals.waitingBody':
    'Each request brings together the transaction, the reason it was flagged, and the decision history in one place.',
  'approvals.waitingTitle': 'What is waiting for approval',
  'reports.categoryMix': 'Category mix',
  'reports.categoryMixBody': 'Where this report is actually spending.',
  'reports.exportLineItemsCsv': 'Export line items CSV',
  'reports.exportViewCsv': 'Export view CSV',
  'reports.generate': 'Generate',
  'reports.generatedOverviewBody': 'The prompt-produced report set from the planned targets.',
  'reports.generatedOverviewTitle': 'Generated report totals',
  'reports.generatedPrepared': 'Prepared for {targets}.',
  'reports.generatedSummary': 'Generated {reports} report{reportsSuffix} from {targets} requested target{targetsSuffix}.',
  'reports.generating': 'Generating...',
  'reports.incompleteCoverage':
    'This report has incomplete scan coverage: {policy} policy items and {risk} risk items are still unscanned.',
  'reports.loadingReports': 'Loading reports...',
  'reports.missingPreapprovals': 'Missing pre-approvals',
  'reports.missingReceipts': 'Missing receipts',
  'reports.noReports': 'No reports yet.',
  'reports.openApprovals': 'Open approvals',
  'reports.policyAndRiskPressure': 'Policy and risk pressure',
  'reports.policyAndRiskPressureBody': 'Which generated reports carry the heaviest review load.',
  'reports.policyFlags': 'Policy flags',
  'reports.reportBody': 'Pick one person or one team and generate a report package you can export.',
  'reports.reportFallback': 'Generated report',
  'reports.reportSelectEmpty': 'Select or generate a report to inspect line items.',
  'reports.riskFlags': 'Risk flags',
  'reports.savedReportsBody': 'Report packages you have already created.',
  'reports.savedReportsTitle': 'Saved reports',
  'reports.spendRhythm': 'Spend rhythm',
  'reports.spendRhythmBody': 'How the selected report moves over time.',
  'reports.startTitle': 'Start a report',
  'reports.total': 'Total',
  'compliance.attentionBody': 'Start with the highest-priority transactions first.',
  'compliance.attentionTitle': 'What needs attention now',
  'compliance.checkIssuesBody': 'Run a fresh review when you want updated policy, risk, and queue results.',
  'compliance.checkIssuesTitle': 'Check for issues',
  'compliance.checkTransactions': 'Check transactions',
  'compliance.combinedFindingsEmpty': 'No combined findings are visible with the current filters.',
  'compliance.flaggedReason': 'Why it was flagged',
  'compliance.groundedReasons': 'Grounded reasons',
  'compliance.groundingWarnings': 'Grounding warnings',
  'compliance.moreFlags': '+{count} more',
  'compliance.next': 'Next:',
  'compliance.noCitations': 'No citations',
  'compliance.noMatches': 'No transactions match the current filters.',
  'compliance.policyCitations': 'Policy citations',
  'compliance.policyClause': 'Policy clause',
  'compliance.quickSummary': 'Quick summary',
  'compliance.reviewItemsBody': 'One row per transaction, with the reason it was flagged and the next step to take.',
  'compliance.reviewItemsTitle': 'Transactions to review',
  'compliance.viewFlagDetails': 'View {count} flag details',
  'transactions.amountCad': 'Amount CAD',
  'transactions.category': 'Category',
  'transactions.clearDataBody':
    'Use this only if you want to start over with a fresh import. Employees and departments stay in place.',
  'transactions.clearDataTitle': 'Clear imported data',
  'transactions.clearImport': 'Clear import',
  'transactions.clearSummary':
    'Cleared {transactions} transactions, {raw} raw rows, {receipts} receipts, {preapprovals} preapprovals, and {remainder}.',
  'transactions.clearing': 'Clearing...',
  'transactions.confirmReset':
    'Delete imported transactions and generated workflow data? This removes transactions, raw imports, receipts, preapprovals, policy checks, violations, and related report items. Employees and departments stay in place.',
  'transactions.country': 'Country',
  'transactions.date': 'Date',
  'transactions.department': 'Department',
  'transactions.description':
    'Browse imported transactions, check the cleaned-up fields, and spot anything off.',
  'transactions.download': 'Download CSV',
  'transactions.employee': 'Employee',
  'transactions.eyebrow': 'Review',
  'transactions.fingerprint': 'Fingerprint',
  'transactions.loading': 'Loading transactions...',
  'transactions.mcc': 'MCC',
  'transactions.merchant': 'Merchant',
  'transactions.noTransactions': 'No transactions imported yet.',
  'transactions.recent': 'Imported transactions',
  'transactions.recentBody': 'These are the cleaned and mapped rows currently in your workspace.',
  'transactions.resetApprovalRequests': 'approval requests',
  'transactions.resetEmptyReports': 'empty reports',
  'transactions.resetPolicyChecks': 'policy checks',
  'transactions.resetReportItems': 'report items',
  'transactions.resetRiskScores': 'risk scores',
  'transactions.syntheticDepartment': 'Assigned department',
  'transactions.syntheticEmployee': 'Assigned employee',
  'transactions.title': 'Transactions',
  'transactions.resetViolations': 'violations',
}

const fr: Record<keyof typeof en, string> = {
  'actions.approve': 'Approuver',
  'actions.import': 'Importer',
  'actions.preview': 'Apercu',
  'actions.refresh': 'Actualiser',
  'actions.runFullScan': 'Analyse complete',
  'actions.scanTransactions': 'Analyser les transactions',
  'actions.scanning': 'Analyse...',
  'app.demoData': 'Donnees de test',
  'app.demoDataBody': 'Des profils, recus, approbations et budgets exemples gardent cet espace sur pour l exploration.',
  'app.name': 'PolyPilot',
  'app.subtitle': 'Copilote finance',
  'app.workspace': 'Espace finance',
  'approvals.description':
    'Transformez les transactions signalees en paquets de decision manager avec contexte de politique, de risque et de budget.',
  'approvals.eyebrow': 'Decision',
  'approvals.title': 'Approbations',
  'compliance.allSeverities': 'Toutes les severites',
  'compliance.allStatuses': 'Tous les statuts',
  'compliance.amountCad': 'Montant CAD',
  'compliance.approvalEvidenceNeeded': 'Preuve d approbation requise',
  'compliance.category': 'Categorie',
  'compliance.compliant': 'Conforme',
  'compliance.contextNeeded': 'Contexte requis',
  'compliance.critical': 'Critique',
  'compliance.date': 'Date',
  'compliance.department': 'Service',
  'compliance.departmentsWithOpenFlags': 'Services avec alertes ouvertes',
  'compliance.description':
    'Voyez quelles transactions meritent une verification, pourquoi elles sont signalees et quoi faire ensuite.',
  'compliance.details': 'Details',
  'compliance.employee': 'Employe',
  'compliance.employeesWithOpenFlags': 'Employes avec alertes ouvertes',
  'compliance.evidenceNote':
    'Le fichier CSV fourni ne contient pas les pieces jointes de recu ou d approbation. Les constats lies aux preuves indiquent les documents exiges par la politique, et non des documents confirmes manquants.',
  'compliance.eyebrow': 'Revue',
  'compliance.excludedNonExpense': 'Hors depense',
  'compliance.filterByPolicyStatus': 'Filtrer par statut',
  'compliance.filterBySeverity': 'Filtrer par severite',
  'compliance.findings': 'Constats par transaction',
  'compliance.findingsBody': 'Une ligne par transaction, avec les details de politique et de risque combines.',
  'compliance.high': 'Elevee',
  'compliance.highCritical': 'Elevee/Critique',
  'compliance.individualFlags': 'Alertes individuelles',
  'compliance.lastScanSummary': 'Derniere analyse terminee en {duration} sur {batches} lots.',
  'compliance.loading': 'Chargement des resultats de politique...',
  'compliance.low': 'Faible',
  'compliance.medium': 'Moyenne',
  'compliance.merchant': 'Marchand',
  'compliance.missing': 'Manquant',
  'compliance.mlProgressTitle': 'Analyse ML en cours',
  'compliance.needContext': 'Contexte requis',
  'compliance.needPreapproval': 'Preuve d approbation requise',
  'compliance.needReceipt': 'Preuve de recu requise',
  'compliance.needsContext': 'Contexte requis',
  'compliance.needsPreapproval': 'Preuve d approbation requise',
  'compliance.needsReceipt': 'Preuve de recu requise',
  'compliance.nextAction': 'Prochaine action',
  'compliance.noFindings': 'Aucun constat de politique pour le moment.',
  'compliance.noOpenPolicyFlags': 'Aucune alerte de politique ouverte.',
  'compliance.policyDetail': 'detail de politique',
  'compliance.policyDetails': 'details de politique',
  'compliance.policyViolation': 'Violation de politique',
  'compliance.policyViolations': 'Violations de politique',
  'compliance.policyScan': 'Analyse de politique',
  'compliance.policyScanBody': 'Execute le flux par couches: conformite, risque, puis file de revue.',
  'compliance.reviewRequired': 'Revision requise',
  'compliance.scanStageFinalizing': 'Finalisation',
  'compliance.scanStageFinalizingBody': 'Mise a jour des resumes, des recidives et des prochaines actions.',
  'compliance.scanStagePolicy': 'Regles de politique',
  'compliance.scanStagePolicyBody': 'Verification des regles televersees sur chaque transaction importee.',
  'compliance.scanStageQueue': 'File de revue',
  'compliance.scanStageQueueBody': 'Fusion des signaux de conformite et de risque en dossiers exploitables.',
  'compliance.scanStageRisk': 'Signaux de risque',
  'compliance.scanStageRiskBody': 'Notation des doublons, fractionnements, avances de fonds, FX et metadonnees manquantes.',
  'compliance.scanned': 'Analysees',
  'compliance.score': 'Score',
  'compliance.severity': 'Severite',
  'compliance.status': 'Statut',
  'compliance.sortedByRisk': 'Trie par severite, score et montant.',
  'compliance.syntheticDepartment': 'Service assigne',
  'compliance.syntheticEmployee': 'Employe assigne',
  'compliance.title': 'File de revue',
  'compliance.violation': 'Violation',
  'compliance.violations': 'Violations',
  'dashboard.backendBoundary': 'Etat de connexion',
  'dashboard.backendChecking': 'Verification de la connexion...',
  'dashboard.backendOffline': 'Connexion indisponible. Vous pouvez quand meme parcourir l espace actuel.',
  'dashboard.backendOnline': 'Connecte et renvoie les totaux en direct.',
  'dashboard.departmentCount': 'Services',
  'dashboard.description':
    'Rencontrez PolyPilot, comprenez l espace de travail et choisissez la suite avec un contexte reel.',
  'dashboard.employeeCount': 'Employes',
  'dashboard.eyebrow': 'Vue d ensemble',
  'dashboard.heroBadge': 'Rencontrez PolyPilot',
  'dashboard.heroDescription':
    'Utilisez un seul espace pour importer les depenses, revoir des signaux de politique et de risque ancres, poser des questions de suivi, puis passer proprement aux approbations ou aux rapports.',
  'dashboard.heroEyebrow': 'Operations finance',
  'dashboard.heroSignalOne': 'Transactions importees',
  'dashboard.heroSignalPending': 'Chargement',
  'dashboard.heroSignalThree': 'A revoir',
  'dashboard.heroSignalThreeValue': 'Pret',
  'dashboard.heroSignalTwo': 'Employes relies',
  'dashboard.heroTitle': 'PolyPilot transforme les depenses importees en decisions finance ancrees.',
  'dashboard.introAskBody': 'Gardez l assistant proche lorsque vous avez besoin d une reponse rapide, d un resume ou d un passage vers la vue Questions.',
  'dashboard.introAskLabel': 'Poser avec contexte',
  'dashboard.introImportBody': 'Importez des exports de carte, normalisez-les et gardez visible le chemin entre brut et nettoye.',
  'dashboard.introImportLabel': 'Partir des donnees importees',
  'dashboard.introReviewBody': 'Politique, risque et approbations restent relies a de vrais enregistrements au lieu d une analytique decorative.',
  'dashboard.introReviewLabel': 'Revoir des signaux ancres',
  'dashboard.normalizedCount': 'Transactions',
  'dashboard.overlayOneLabel': 'Controles politique',
  'dashboard.overlayOneValue': 'Seuils surveilles',
  'dashboard.overlayThreeLabel': 'Exemple voyage',
  'dashboard.overlayThreeValue': 'Depenses de voyage marketing',
  'dashboard.overlayTwoLabel': 'Revue risque',
  'dashboard.overlayTwoValue': 'Signaux prets',
  'dashboard.rawRows': 'Lignes brutes',
  'dashboard.primaryAction': 'Commencer l import',
  'dashboard.sceneBadge': 'Vue en direct',
  'dashboard.sceneBody': 'Une sphere neurale transforme les depenses importees en signaux relies, impulsions d analyse et alertes visibles.',
  'dashboard.sceneLabel': 'Carte neurale des depenses',
  'dashboard.secondaryAction': 'Parler a Poly',
  'dashboard.signalBody': 'Voici les seuls signaux en direct montres ici : l etat de connexion et la couverture des donnees importees.',
  'dashboard.signalConnection': 'Connexion',
  'dashboard.signalConnectionChecking': 'Verification',
  'dashboard.signalConnectionOffline': 'Indisponible',
  'dashboard.signalConnectionOnline': 'Connecte',
  'dashboard.signalDepartments': 'Services relies',
  'dashboard.signalFootnote': 'Cette vue reste volontairement introductive. Les compteurs plus profonds et la pression de revue vivent dans les pages de workflow ou ils peuvent etre expliques.',
  'dashboard.signalImported': 'Transactions importees',
  'dashboard.signalPeople': 'Employes relies',
  'dashboard.signalTitle': 'Signaux de l espace',
  'dashboard.signalUnavailable': 'Indisponible',
  'dashboard.storyPrimaryLabel': 'Lead finance',
  'dashboard.storyPrimaryValue': 'Passez de l import a la decision sans quitter le workspace.',
  'dashboard.storySecondaryLabel': 'Couche controle',
  'dashboard.storySecondaryValue': 'Politique, risque et approbations restent ancres dans les donnees persistees.',
  'dashboard.storyTertiaryLabel': 'Pulse operations',
  'dashboard.storyTertiaryValue': 'Gardez le prochain dossier de depenses pret pour revue au premier plan.',
  'dashboard.title': 'Vue d ensemble',
  'dashboard.workflowApproveBody': 'Ouvrez des decisions pretes pour manager avec le contexte de politique, risque, budget et recommandation deja rassemble.',
  'dashboard.workflowApproveLabel': 'Approuver',
  'dashboard.workflowBody': 'Cette route sert a orienter l equipe, pas a la noyer dans des graphiques. Suivez ce flux quand vous etes pret a travailler.',
  'dashboard.workflowImportBody': 'Chargez un export de carte, previsualisez le nettoyage, puis etablissez les donnees source utilisees par PolyPilot.',
  'dashboard.workflowImportLabel': 'Importer',
  'dashboard.workflowReportBody': 'Generez des dossiers de rapport seulement lorsque les enregistrements et l etat de revue sont prets a voyager avec eux.',
  'dashboard.workflowReportLabel': 'Rapport',
  'dashboard.workflowReviewBody': 'Voyez quelles transactions demandent une attention et pourquoi, avec des constats ancres plutot que des metriques decoratives.',
  'dashboard.workflowReviewLabel': 'Revoir',
  'dashboard.workflowTitle': 'Comment l espace fonctionne',
  'import.amountCad': 'Montant CAD',
  'import.category': 'Categorie',
  'import.chooseCsv': 'Choisir un fichier CSV',
  'import.csvText': 'Texte CSV',
  'import.dataSourceHint': 'Donnees separees par virgules ou tabulations',
  'import.date': 'Date',
  'import.description':
    'Importez un export de carte, verifiez les lignes nettoyees, puis ajoutez-les a votre espace de travail.',
  'import.errorsTitle': 'Erreurs de lignes',
  'import.eyebrow': 'Import',
  'import.fingerprint': 'Empreinte',
  'import.importComplete': 'Import termine',
  'import.inserted': 'Insere',
  'import.merchant': 'Marchand',
  'import.missingColumns': 'Colonnes manquantes',
  'import.missingColumnsTitle': 'Colonnes requises manquantes',
  'import.placeholder': 'Collez les lignes CSV ou TSV ici',
  'import.previewTitle': 'Apercu',
  'import.previewBody': 'Verifiez les lignes nettoyees avant de les ajouter.',
  'import.previewRowsLabel': 'Lignes en apercu',
  'import.readinessLabel': 'Etat de l import',
  'import.readinessNeedsAttention': 'A verifier',
  'import.readinessReady': 'Pret',
  'import.row': 'Ligne',
  'import.rowErrors': 'Erreurs',
  'import.rowsReady': 'Lignes pretes',
  'import.sourceLabel': 'Source',
  'import.sourcePasted': 'Texte CSV colle',
  'import.skipped': 'Ignore',
  'import.statusTitle': 'Statut d import',
  'import.syntheticEmployee': 'Employe assigne',
  'import.title': 'Import',
  'import.transactions': 'transactions.',
  'import.unassigned': 'Non assigne',
  'policyRules.description':
    'Revisez les regles de remboursement, redigez de nouvelles logiques de politique et testez l activation via le service backend.',
  'policyRules.eyebrow': 'Configuration',
  'policyRules.title': 'Configuration de politique',
  'policyRules.activate': 'Activer',
  'policyRules.activationNote':
    'Les brouillons et regles desactivees peuvent etre modifies sans effet. Seules les regles actives sont appliquees dans les scans et visibles dans Conformite.',
  'policyRules.activated': 'Regle activee.',
  'policyRules.active': 'Active',
  'policyRules.allRules': 'Toutes les regles',
  'policyRules.critical': 'Critique',
  'policyRules.disabled': 'Regle desactivee.',
  'policyRules.disabledStatus': 'Desactivee',
  'policyRules.disable': 'Desactiver',
  'policyRules.draft': 'Brouillon',
  'policyRules.draftJson': 'Apercu JSON brouillon',
  'policyRules.draftWorkbench': 'Atelier brouillon',
  'policyRules.draftWorkbenchBody': 'Collez le texte de politique, faconnez une regle JSON, puis validez avant activation.',
  'policyRules.high': 'Elevee',
  'policyRules.invalidJson': 'Le JSON brouillon n est pas valide.',
  'policyRules.invalidRule': 'Regle invalide',
  'policyRules.loadError': 'Impossible de charger les regles.',
  'policyRules.loading': 'Chargement des regles...',
  'policyRules.low': 'Faible',
  'policyRules.manualDraftDescription': 'Regle brouillon manuelle depuis l atelier de politiques.',
  'policyRules.matchedCount': '{count} correspondances exemple',
  'policyRules.medium': 'Moyenne',
  'policyRules.noRules': 'Aucune regle pour ce filtre.',
  'policyRules.policyText': 'Texte de politique',
  'policyRules.policyTextPlaceholder': 'Collez ici une clause de remboursement ou une regle de depense manager.',
  'policyRules.ruleCode': 'Code de regle',
  'policyRules.ruleLibrary': 'Bibliotheque de regles',
  'policyRules.ruleLibraryBody': 'Les regles seed et manager restent editables via les endpoints backend.',
  'policyRules.ruleName': 'Nom de regle',
  'policyRules.runScan': 'Lancer scan',
  'policyRules.saveDraft': 'Sauver brouillon',
  'policyRules.saveError': 'Impossible de sauver la regle brouillon.',
  'policyRules.savedDraft': 'Regle brouillon sauvee.',
  'policyRules.scanComplete': 'Scan termine: {count} transactions scannees, {flags} details de politique enregistres.',
  'policyRules.scanError': 'Impossible de lancer le scan.',
  'policyRules.saving': 'Sauvegarde...',
  'policyRules.severity': 'Severite',
  'policyRules.test': 'Tester',
  'policyRules.testError': 'Impossible de tester la regle.',
  'policyRules.testing': 'Test...',
  'policyRules.testResult': 'Resultat du test',
  'policyRules.updateError': 'Impossible de mettre a jour la regle.',
  'policyRules.validateTest': 'Valider/tester',
  'policyRules.validationFailed': 'La validation de regle demande attention.',
  'policyRules.validationPassed': 'Validation de regle reussie.',
  'policyRules.validRule': 'Regle valide',
  'reports.description':
    'Generez des rapports de depenses avec lignes detaillees, alertes de politique, alertes de risque, resumes concis et export CSV.',
  'reports.eyebrow': 'Rapport',
  'reports.title': 'Rapports',
  'routes.approvals.description': 'Traitez les decisions en attente d un manager.',
  'routes.approvals.label': 'Approbations',
  'routes.compliance.description': 'Voyez quelles transactions meritent une verification.',
  'routes.compliance.label': 'Revue',
  'routes.dashboard.description': 'Rencontrez PolyPilot, verifiez l etat de l espace et choisissez la suite.',
  'routes.dashboard.label': 'Vue d ensemble',
  'routes.import.description': 'Importez un export de carte et ajoutez les lignes nettoyees.',
  'routes.import.label': 'Import',
  'routes.policyRules.description': 'Gerez les regles derriere votre flux de revue.',
  'routes.policyRules.label': 'Configuration de politique',
  'routes.reports.description': 'Creez et exportez des dossiers de depenses.',
  'routes.reports.label': 'Rapports',
  'routes.talkToData.description': 'Posez des questions simples sur les depenses.',
  'routes.talkToData.label': 'Questions',
  'routes.transactions.description': 'Parcourez les transactions nettoyees et reliees.',
  'routes.transactions.label': 'Transactions',
  'scaffold.aiBoundary': 'Garde-fous',
  'scaffold.aiBoundaryBody': 'Les reponses et automatisations restent dans des regles backend validees.',
  'scaffold.currentMilestone': 'Ce que cette page aide a faire',
  'scaffold.currentMilestoneBody': 'Commencez par l import, puis passez a la revue et aux approbations.',
  'scaffold.dataSource': 'Donnees importees',
  'scaffold.dataSourceBody': 'Transactions, constats et historique de workflow vivent au meme endroit.',
  'shell.collapseSidebar': 'Replier la barre laterale',
  'shell.expandSidebar': 'Deplier la barre laterale',
  'shell.language': 'English',
  'shell.notifications': 'Notifications',
  'shell.search': 'Recherche',
  'shell.switchLanguage': 'Changer de langue',
  'shell.switchTheme': 'Changer de theme',
  'shell.themeDark': 'Mode nuit',
  'shell.themeLight': 'Mode jour',
  'talkToData.description':
    'Posez des questions simples sur les depenses et obtenez des reponses fiables et ancrees dans les donnees.',
  'talkToData.eyebrow': 'Questions',
  'talkToData.activeContext': 'Contexte {title} actif',
  'talkToData.activeSession': 'Session {id} active',
  'talkToData.artifactCurrent': 'Artefact actuel',
  'talkToData.artifactPreview': 'Apercu {label}',
  'talkToData.artifacts': 'Artefacts',
  'talkToData.ask': 'Poser',
  'talkToData.asking': 'Question en cours...',
  'talkToData.chatFirstBody':
    'Poly dans le dock et cet espace complet partagent la meme session. Vous pouvez commencer n importe ou et venir ici quand la reponse a besoin de plus d espace.',
  'talkToData.chatFirstTitle': 'Commencer par discuter',
  'talkToData.citations': 'Citations',
  'talkToData.conversation': 'Conversation',
  'talkToData.conversationBody':
    'Posez vos questions naturellement, poursuivez la conversation et utilisez le contexte de la page quand c est utile.',
  'talkToData.copyPreview': 'Copier l apercu',
  'talkToData.dismiss': 'Fermer',
  'talkToData.downloadBrief': 'Telecharger le brief',
  'talkToData.downloadCsv': 'Telecharger le CSV',
  'talkToData.downloadDiagram': 'Telecharger le diagramme',
  'talkToData.downloadPreview': 'Telecharger l apercu',
  'talkToData.emptyGrounding':
    'Les questions de politique peuvent citer des clauses retrouvees et des constats signales.',
  'talkToData.emptySpend':
    'Les questions sur les depenses renvoient des totaux, comptes, moyennes et regroupements.',
  'talkToData.emptyWorkspace':
    'Utilisez le dock depuis n importe quelle page, puis venez ici quand la reponse a besoin de graphiques, tableaux ou exports.',
  'talkToData.filtersAndFocus': 'Filtres et focus',
  'talkToData.generatedFiles': 'Fichiers generes',
  'talkToData.generatedFilesBody':
    'Previsualisez l artefact tout de suite, puis telechargez un fichier genere par le backend quand vous voulez le garder.',
  'talkToData.grounding': 'Ancrage',
  'talkToData.loadingSession': 'Chargement de la session',
  'talkToData.newSession': 'Nouvelle session',
  'talkToData.noExtraFilters': 'Cette reponse n avait pas besoin de filtres supplementaires.',
  'talkToData.noRows': 'Aucune ligne retournee pour cette question.',
  'talkToData.overview': 'Vue d ensemble',
  'talkToData.placeholder': 'Posez une question sur les depenses, la politique ou le risque...',
  'talkToData.result': 'Resultat',
  'talkToData.resultPreview': 'Apercu du resultat',
  'talkToData.selectedAnswer': 'Reponse selectionnee',
  'talkToData.selectedAnswerEmpty': 'Choisissez une reponse de l assistant pour voir le plan, les resultats et les exports.',
  'talkToData.suggestedAsks': 'Questions suggerees',
  'talkToData.title': 'Poser une question',
  'talkToData.valid': 'Valide',
  'talkToData.validated': 'Valide',
  'talkToData.validation': 'Validation',
  'talkToData.validationBody':
    'Les demandes sont validees avant tout flux backend. Les plans non pris en charge sont bloques avant execution.',
  'talkToData.blocked': 'Bloque',
  'approvals.advisoryRecommendation': 'Recommandation consultative',
  'approvals.allApprovals': 'Toutes les approbations',
  'approvals.approved': 'Approuve',
  'approvals.approving': 'Approbation...',
  'approvals.budgetSnapshot': 'Apercu budgetaire',
  'approvals.budgetUnavailable': 'Aucun apercu budgetaire disponible.',
  'approvals.cancelled': 'Annule',
  'approvals.creating': 'Creation...',
  'approvals.decision': 'Decision',
  'approvals.decisionNote': 'Note de decision',
  'approvals.decisionPacket': 'Dossier de decision',
  'approvals.decisionPacketBody':
    'Selectionnez ou creez une demande d approbation pour voir la recommandation, le contexte budgetaire et les controles de decision prets pour audit.',
  'approvals.decisionSaved': 'Decision enregistree par {actor}{timestamp}.',
  'approvals.decided': 'Decidees',
  'approvals.denied': 'Refuse',
  'approvals.deny': 'Refuser',
  'approvals.denying': 'Refus...',
  'approvals.filterStatus': 'Filtrer le statut d approbation',
  'approvals.groundedInputs': 'Elements ancres',
  'approvals.loadingApprovals': 'Chargement des approbations...',
  'approvals.loadingCandidates': 'Chargement des candidatures a l approbation...',
  'approvals.managerDecisionBody':
    'Commencez ici lorsqu une transaction signalee a besoin de quelqu un pour decider de la suite.',
  'approvals.managerDecisionTitle': 'Decision manager requise',
  'approvals.missingInformation': 'Informations manquantes',
  'approvals.monthRemaining': 'Reste du mois',
  'approvals.needsDecision': 'Decision requise',
  'approvals.noApprovals': 'Aucune demande d approbation pour le moment.',
  'approvals.noManagerWaiting': 'Aucune transaction n attend un manager pour le moment.',
  'approvals.noneRecorded': 'Aucun element.',
  'approvals.openApproval': 'Ouvrir l approbation',
  'approvals.openApprovals': 'Approbations ouvertes',
  'approvals.priorApprovals': 'Approbations precedentes',
  'approvals.priority': 'Priorite {value}',
  'approvals.quarterRemaining': 'Reste du trimestre',
  'approvals.quarterSpend': 'Depense du trimestre',
  'approvals.recommend': 'Recommande {value}',
  'approvals.refresh': 'Actualiser',
  'approvals.requested': 'Demandee',
  'approvals.reviewerBrief': 'Resume du reviseur',
  'approvals.savedApprovalsBody': 'Demandes deja creees.',
  'approvals.savedApprovalsTitle': 'Approbations enregistrees',
  'approvals.saving': 'Enregistrement...',
  'approvals.spendHistory': 'Historique des depenses de l employe',
  'approvals.spendHistoryUnavailable': 'Aucun apercu de l historique de depenses disponible.',
  'approvals.totalSpend': 'Depense totale',
  'approvals.transactions': 'Transactions',
  'approvals.urgent': 'Urgent',
  'approvals.waitingBody':
    'Chaque demande regroupe la transaction, la raison du signalement et l historique des decisions au meme endroit.',
  'approvals.waitingTitle': 'Ce qui attend une approbation',
  'reports.categoryMix': 'Repartition par categorie',
  'reports.categoryMixBody': 'Ou ce rapport depense reellement.',
  'reports.exportLineItemsCsv': 'Exporter le CSV des lignes',
  'reports.exportViewCsv': 'Exporter la vue CSV',
  'reports.generate': 'Generer',
  'reports.generatedOverviewBody': 'L ensemble de rapports produit a partir des cibles prevues par la demande.',
  'reports.generatedOverviewTitle': 'Totaux des rapports generes',
  'reports.generatedPrepared': 'Prepare pour {targets}.',
  'reports.generatedSummary':
    'Generation de {reports} rapport{reportsSuffix} a partir de {targets} cible{targetsSuffix} demandee{targetsSuffix}.',
  'reports.generating': 'Generation...',
  'reports.incompleteCoverage':
    'Ce rapport a une couverture d analyse incomplete : {policy} elements de politique et {risk} elements de risque ne sont pas encore analyses.',
  'reports.loadingReports': 'Chargement des rapports...',
  'reports.missingPreapprovals': 'Preapprobations manquantes',
  'reports.missingReceipts': 'Recus manquants',
  'reports.noReports': 'Aucun rapport pour le moment.',
  'reports.openApprovals': 'Approbations ouvertes',
  'reports.policyAndRiskPressure': 'Pression politique et risque',
  'reports.policyAndRiskPressureBody':
    'Quels rapports generes portent la charge de revue la plus lourde.',
  'reports.policyFlags': 'Alertes de politique',
  'reports.reportBody': 'Choisissez une personne ou une equipe et generez un dossier de rapport exportable.',
  'reports.reportFallback': 'Rapport genere',
  'reports.reportSelectEmpty': 'Selectionnez ou generez un rapport pour voir les lignes.',
  'reports.riskFlags': 'Alertes de risque',
  'reports.savedReportsBody': 'Dossiers de rapport deja crees.',
  'reports.savedReportsTitle': 'Rapports enregistres',
  'reports.spendRhythm': 'Rythme des depenses',
  'reports.spendRhythmBody': 'Comment le rapport selectionne evolue dans le temps.',
  'reports.startTitle': 'Commencer un rapport',
  'reports.total': 'Total',
  'compliance.attentionBody': 'Commencez par les transactions les plus prioritaires.',
  'compliance.attentionTitle': 'Ce qui demande une attention immediate',
  'compliance.checkIssuesBody':
    'Lancez une nouvelle revue lorsque vous voulez des resultats de politique, de risque et de file mis a jour.',
  'compliance.checkIssuesTitle': 'Verifier les problemes',
  'compliance.checkTransactions': 'Verifier les transactions',
  'compliance.combinedFindingsEmpty':
    'Aucun constat combine n est visible avec les filtres actuels.',
  'compliance.flaggedReason': 'Pourquoi c est signale',
  'compliance.groundedReasons': 'Raisons ancrees',
  'compliance.groundingWarnings': 'Avertissements d ancrage',
  'compliance.moreFlags': '+{count} de plus',
  'compliance.next': 'Suite :',
  'compliance.noCitations': 'Aucune citation',
  'compliance.noMatches': 'Aucune transaction ne correspond aux filtres actuels.',
  'compliance.policyCitations': 'Citations de politique',
  'compliance.policyClause': 'Clause de politique',
  'compliance.quickSummary': 'Resume rapide',
  'compliance.reviewItemsBody':
    'Une ligne par transaction, avec la raison du signalement et la prochaine etape.',
  'compliance.reviewItemsTitle': 'Transactions a revoir',
  'compliance.viewFlagDetails': 'Voir les details de {count} alerte(s)',
  'transactions.amountCad': 'Montant CAD',
  'transactions.category': 'Categorie',
  'transactions.clearDataBody':
    'Utilisez ceci seulement si vous voulez recommencer avec un nouvel import. Les employes et les services restent en place.',
  'transactions.clearDataTitle': 'Effacer les donnees importees',
  'transactions.clearImport': 'Effacer l import',
  'transactions.clearSummary':
    'Suppression de {transactions} transactions, {raw} lignes brutes, {receipts} recus, {preapprovals} preapprobations et {remainder}.',
  'transactions.clearing': 'Suppression...',
  'transactions.confirmReset':
    'Supprimer les transactions importees et les donnees de workflow generees? Cela efface les transactions, imports bruts, recus, preapprobations, controles de politique, violations et elements de rapport associes. Les employes et les services restent en place.',
  'transactions.country': 'Pays',
  'transactions.date': 'Date',
  'transactions.department': 'Service',
  'transactions.description':
    'Parcourez les transactions importees, verifiez les champs nettoyes et reperez ce qui semble incorrect.',
  'transactions.download': 'Telecharger le CSV',
  'transactions.employee': 'Employe',
  'transactions.eyebrow': 'Revue',
  'transactions.fingerprint': 'Empreinte',
  'transactions.loading': 'Chargement des transactions...',
  'transactions.mcc': 'MCC',
  'transactions.merchant': 'Marchand',
  'transactions.noTransactions': 'Aucune transaction importee.',
  'transactions.recent': 'Transactions importees',
  'transactions.recentBody': 'Voici les lignes nettoyees et reliees presentes dans votre espace de travail.',
  'transactions.resetApprovalRequests': 'demandes d approbation',
  'transactions.resetEmptyReports': 'rapports vides',
  'transactions.resetPolicyChecks': 'controles de politique',
  'transactions.resetReportItems': 'elements de rapport',
  'transactions.resetRiskScores': 'scores de risque',
  'transactions.syntheticDepartment': 'Service assigne',
  'transactions.syntheticEmployee': 'Employe assigne',
  'transactions.title': 'Transactions',
  'transactions.resetViolations': 'violations',
}

export const dictionaries = { en, fr }

export type TranslationKey = keyof typeof en

export const localeByLanguage: Record<Language, string> = {
  en: 'en-CA',
  fr: 'fr-CA',
}

export const UiPreferencesContext = createContext<UiPreferencesContextValue | null>(null)

export function getStoredThemeMode(): ThemeMode {
  if (typeof window === 'undefined') {
    return 'light'
  }

  const storedTheme = window.localStorage.getItem(uiStorageKeys.themeMode)

  if (storedTheme === 'dark' || storedTheme === 'light') {
    return storedTheme
  }

  return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'
}

export function getStoredLanguage(): Language {
  if (typeof window === 'undefined') {
    return 'en'
  }

  const storedLanguage = window.localStorage.getItem(uiStorageKeys.language)

  return storedLanguage === 'fr' ? 'fr' : 'en'
}

export function getStoredSidebarCollapsed() {
  if (typeof window === 'undefined') {
    return false
  }

  return window.localStorage.getItem(uiStorageKeys.sidebarCollapsed) === 'true'
}

export function useUiPreferences() {
  const value = useContext(UiPreferencesContext)

  if (!value) {
    throw new Error('useUiPreferences must be used within UiPreferencesProvider.')
  }

  return value
}
