update public.policy_rules
set
  active = false,
  enabled = false,
  status = 'draft',
  validation_errors = (
    select jsonb_agg(distinct value)
    from jsonb_array_elements_text(
      coalesce(validation_errors, '[]'::jsonb)
      || '["Activation blocked: existing AI-extracted rules must be reviewed under synthetic evidence guardrails before enforcement."]'::jsonb
    ) as value
  ),
  updated_at = now()
where source_type = 'ai_extracted'
  and status = 'active';

insert into public.policy_rules (
  rule_code,
  title,
  description,
  severity,
  deterministic,
  active,
  synthetic,
  name,
  enabled,
  status,
  rule_kind,
  config_schema_version,
  condition,
  outcome,
  scope,
  rule_json,
  conditions_json,
  outcome_json,
  scope_json,
  applies_to_json,
  context_requirements_json,
  requires_json,
  validation_errors,
  rule_metadata,
  source_type
)
values
  (
    'PREAPPROVAL_OVER_50',
    'Expenses over $50 require manager pre-authorization',
    'Expenses over CAD 50 require manager pre-authorization before reimbursement or approval.',
    'high',
    true,
    true,
    true,
    'Expenses over $50 require manager pre-authorization',
    true,
    'active',
    'json_config',
    1,
    '{"all":[{"field":"skips_normal_expense_rules","operator":"is_false"},{"field":"amount_cad","operator":"gt","value":{"threshold":"preapproval_threshold_cad"}},{"field":"missing_preapproval","operator":"is_true"}]}'::jsonb,
    '{"status":"approval_evidence_needed","violation":{"rule_code":"PREAPPROVAL_OVER_50","severity":"high","explanation":"This transaction exceeds the active preapproval threshold and is missing approval evidence.","required_action":"Collect or document the required preapproval evidence before approval."},"missing_information":["manager pre-authorization evidence"]}'::jsonb,
    '{"department_ids":[],"employee_ids":[]}'::jsonb,
    '{"rule_code":"PREAPPROVAL_OVER_50","name":"Expenses over $50 require manager pre-authorization","enabled":true,"severity":"high","condition":{"all":[{"field":"skips_normal_expense_rules","operator":"is_false"},{"field":"amount_cad","operator":"gt","value":{"threshold":"preapproval_threshold_cad"}},{"field":"missing_preapproval","operator":"is_true"}]},"outcome":{"status":"approval_evidence_needed","violation":{"rule_code":"PREAPPROVAL_OVER_50","severity":"high","explanation":"This transaction exceeds the active preapproval threshold and is missing approval evidence.","required_action":"Collect or document the required preapproval evidence before approval."},"missing_information":["manager pre-authorization evidence"]},"scope":{"department_ids":[],"employee_ids":[]},"applies_to":{},"context_requirements":[],"requires":{}}'::jsonb,
    '{"all":[{"field":"skips_normal_expense_rules","operator":"is_false"},{"field":"amount_cad","operator":"gt","value":{"threshold":"preapproval_threshold_cad"}},{"field":"missing_preapproval","operator":"is_true"}]}'::jsonb,
    '{"status":"approval_evidence_needed","violation":{"rule_code":"PREAPPROVAL_OVER_50","severity":"high","explanation":"This transaction exceeds the active preapproval threshold and is missing approval evidence.","required_action":"Collect or document the required preapproval evidence before approval."},"missing_information":["manager pre-authorization evidence"]}'::jsonb,
    '{"department_ids":[],"employee_ids":[]}'::jsonb,
    '{}'::jsonb,
    '[]'::jsonb,
    '{}'::jsonb,
    '[]'::jsonb,
    '{"source":"synthetic_evidence_guardrails"}'::jsonb,
    'seeded'
  ),
  (
    'PREAPPROVAL_PENDING_REVIEW',
    'Pending preapproval requires review',
    'Transactions above the preapproval threshold stay in review while approval evidence is still pending.',
    'medium',
    true,
    true,
    true,
    'Pending preapproval requires review',
    true,
    'active',
    'json_config',
    1,
    '{"all":[{"field":"skips_normal_expense_rules","operator":"is_false"},{"field":"requires_preapproval","operator":"is_true"},{"field":"has_pending_preapproval","operator":"is_true"}]}'::jsonb,
    '{"status":"review_required","violation":{"rule_code":"PREAPPROVAL_PENDING_REVIEW","severity":"medium","explanation":"This transaction still has pending preapproval evidence.","required_action":"Follow up on the pending preapproval before approving reimbursement."}}'::jsonb,
    '{"department_ids":[],"employee_ids":[]}'::jsonb,
    '{"rule_code":"PREAPPROVAL_PENDING_REVIEW","name":"Pending preapproval requires review","enabled":true,"severity":"medium","condition":{"all":[{"field":"skips_normal_expense_rules","operator":"is_false"},{"field":"requires_preapproval","operator":"is_true"},{"field":"has_pending_preapproval","operator":"is_true"}]},"outcome":{"status":"review_required","violation":{"rule_code":"PREAPPROVAL_PENDING_REVIEW","severity":"medium","explanation":"This transaction still has pending preapproval evidence.","required_action":"Follow up on the pending preapproval before approving reimbursement."}},"scope":{"department_ids":[],"employee_ids":[]},"applies_to":{},"context_requirements":[],"requires":{}}'::jsonb,
    '{"all":[{"field":"skips_normal_expense_rules","operator":"is_false"},{"field":"requires_preapproval","operator":"is_true"},{"field":"has_pending_preapproval","operator":"is_true"}]}'::jsonb,
    '{"status":"review_required","violation":{"rule_code":"PREAPPROVAL_PENDING_REVIEW","severity":"medium","explanation":"This transaction still has pending preapproval evidence.","required_action":"Follow up on the pending preapproval before approving reimbursement."}}'::jsonb,
    '{"department_ids":[],"employee_ids":[]}'::jsonb,
    '{}'::jsonb,
    '[]'::jsonb,
    '{}'::jsonb,
    '[]'::jsonb,
    '{"source":"synthetic_evidence_guardrails"}'::jsonb,
    'seeded'
  ),
  (
    'RECEIPT_REQUIRED',
    'Receipts are required before reimbursement',
    'Receipts must be submitted before reimbursement can be completed.',
    'medium',
    true,
    true,
    true,
    'Receipts are required before reimbursement',
    true,
    'active',
    'json_config',
    1,
    '{"all":[{"field":"skips_normal_expense_rules","operator":"is_false"},{"field":"receipt_explicitly_missing","operator":"is_true"}]}'::jsonb,
    '{"status":"approval_evidence_needed","violation":{"rule_code":"RECEIPT_REQUIRED","severity":"medium","explanation":"This transaction is explicitly missing required receipt evidence.","required_action":"Collect and attach the required receipt evidence before approval."}}'::jsonb,
    '{"department_ids":[],"employee_ids":[]}'::jsonb,
    '{"rule_code":"RECEIPT_REQUIRED","name":"Receipts are required before reimbursement","enabled":true,"severity":"medium","condition":{"all":[{"field":"skips_normal_expense_rules","operator":"is_false"},{"field":"receipt_explicitly_missing","operator":"is_true"}]},"outcome":{"status":"approval_evidence_needed","violation":{"rule_code":"RECEIPT_REQUIRED","severity":"medium","explanation":"This transaction is explicitly missing required receipt evidence.","required_action":"Collect and attach the required receipt evidence before approval."}},"scope":{"department_ids":[],"employee_ids":[]},"applies_to":{},"context_requirements":[],"requires":{}}'::jsonb,
    '{"all":[{"field":"skips_normal_expense_rules","operator":"is_false"},{"field":"receipt_explicitly_missing","operator":"is_true"}]}'::jsonb,
    '{"status":"approval_evidence_needed","violation":{"rule_code":"RECEIPT_REQUIRED","severity":"medium","explanation":"This transaction is explicitly missing required receipt evidence.","required_action":"Collect and attach the required receipt evidence before approval."}}'::jsonb,
    '{"department_ids":[],"employee_ids":[]}'::jsonb,
    '{}'::jsonb,
    '[]'::jsonb,
    '{}'::jsonb,
    '[]'::jsonb,
    '{"source":"synthetic_evidence_guardrails"}'::jsonb,
    'seeded'
  ),
  (
    'RECEIPT_EVIDENCE_REQUIRED',
    'Receipt evidence readiness required',
    'Receipt-sensitive expenses require receipt evidence to be present or collected before final reimbursement review.',
    'low',
    true,
    true,
    true,
    'Receipt evidence readiness required',
    true,
    'active',
    'json_config',
    1,
    '{"all":[{"field":"skips_normal_expense_rules","operator":"is_false"},{"field":"receipt_sensitive_category","operator":"is_true"},{"field":"receipt_evidence_unavailable","operator":"is_true"},{"field":"receipt_explicitly_missing","operator":"is_false"}]}'::jsonb,
    '{"status":"review_required","violation":{"rule_code":"RECEIPT_EVIDENCE_REQUIRED","severity":"low","explanation":"Receipt-sensitive spend has unavailable receipt evidence in the current dataset.","required_action":"Collect receipt evidence during reimbursement review if reimbursement proceeds."}}'::jsonb,
    '{"department_ids":[],"employee_ids":[]}'::jsonb,
    '{"rule_code":"RECEIPT_EVIDENCE_REQUIRED","name":"Receipt evidence readiness required","enabled":true,"severity":"low","condition":{"all":[{"field":"skips_normal_expense_rules","operator":"is_false"},{"field":"receipt_sensitive_category","operator":"is_true"},{"field":"receipt_evidence_unavailable","operator":"is_true"},{"field":"receipt_explicitly_missing","operator":"is_false"}]},"outcome":{"status":"review_required","violation":{"rule_code":"RECEIPT_EVIDENCE_REQUIRED","severity":"low","explanation":"Receipt-sensitive spend has unavailable receipt evidence in the current dataset.","required_action":"Collect receipt evidence during reimbursement review if reimbursement proceeds."}},"scope":{"department_ids":[],"employee_ids":[]},"applies_to":{},"context_requirements":[],"requires":{}}'::jsonb,
    '{"all":[{"field":"skips_normal_expense_rules","operator":"is_false"},{"field":"receipt_sensitive_category","operator":"is_true"},{"field":"receipt_evidence_unavailable","operator":"is_true"},{"field":"receipt_explicitly_missing","operator":"is_false"}]}'::jsonb,
    '{"status":"review_required","violation":{"rule_code":"RECEIPT_EVIDENCE_REQUIRED","severity":"low","explanation":"Receipt-sensitive spend has unavailable receipt evidence in the current dataset.","required_action":"Collect receipt evidence during reimbursement review if reimbursement proceeds."}}'::jsonb,
    '{"department_ids":[],"employee_ids":[]}'::jsonb,
    '{}'::jsonb,
    '[]'::jsonb,
    '{}'::jsonb,
    '[]'::jsonb,
    '{"source":"synthetic_evidence_guardrails"}'::jsonb,
    'seeded'
  )
on conflict (rule_code) do update
set
  title = excluded.title,
  description = excluded.description,
  severity = excluded.severity,
  deterministic = excluded.deterministic,
  active = excluded.active,
  synthetic = excluded.synthetic,
  name = excluded.name,
  enabled = excluded.enabled,
  status = excluded.status,
  rule_kind = excluded.rule_kind,
  config_schema_version = excluded.config_schema_version,
  condition = excluded.condition,
  outcome = excluded.outcome,
  scope = excluded.scope,
  rule_json = excluded.rule_json,
  conditions_json = excluded.conditions_json,
  outcome_json = excluded.outcome_json,
  scope_json = excluded.scope_json,
  applies_to_json = excluded.applies_to_json,
  context_requirements_json = excluded.context_requirements_json,
  requires_json = excluded.requires_json,
  validation_errors = excluded.validation_errors,
  rule_metadata = coalesce(public.policy_rules.rule_metadata, '{}'::jsonb) || excluded.rule_metadata,
  source_type = excluded.source_type,
  updated_at = now();

delete from public.violations;
delete from public.policy_checks;
